#!/bin/bash

export NAME=`basename $1 .yaml`

export INPUT_YAML=input/${NAME}.yaml
export OUTPUT_PS=${NAME}.ps

if [ `basename $0` == 'holes' ] ; then
  export PARAM='-p BW=1 -p style=holes'
  export OUTPUT_PDF=paper/${NAME}_holes.pdf
else
  export OUTPUT_PDF=output/${NAME}.pdf
fi

perl ThreadPictures.pl -i $INPUT_YAML -o $OUTPUT_PS $PARAM
ps2pdf $OUTPUT_PS $OUTPUT_PDF 2>/dev/null
rm -f $OUTPUT_PS
